project:
  type: website

format:
  html:
    theme: cosmo
    css: assets/css/styles.css
    toc: true
    toc-depth: 3
    code-fold: true

execute:
  freeze: auto
  echo: true

website:
  search: true
  title: "Photonics"
  page-navigation: true
  navbar:
    background: primary
    search: true
    right:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "floating" # Options: "floating", "sticky"
    logo: assets/images/mona_logo.png
    collapse-level: 3
    contents:
      - text: Home
        href: index.qmd
      - text: "---" # This creates a divider
      - section: "Course Info"
        contents:
          - text: Instructor
            href: course-info/intructors.qmd
          - text: Schedule
            href: course-info/schedule.qmd
          - text: Ressources
            href: course-info/resources.qmd
          - text: Lab Course
            href: course-info/labcourse.qmd
          - text: Exams
            href: course-info/exam.qmd
      - text: "---" # This creates a divider
      - section: FOUNDATIONS OF PHOTONICS
        contents:
          - section: "Lecture 1"
            contents:
              - text: Ray Optics
                href: lectures/lecture01/01-lecture01.qmd
          - section: "Lecture 2"
            contents:
              - text: Matrix Optics
                href: lectures/lecture02/01-lecture02.qmd
              - text: Wave Optics Introduction
                href: lectures/lecture02/02-lecture02.qmd
          - section: "Lecture 3"
            contents:
              - text: Interference
                href: lectures/lecture03/01-lecture03.qmd
          - section: "Lecture 4"
            contents:
              - text: Gaussian Beams
                href: lectures/lecture04/01-lecture04.qmd
      - text: "---" # This creates a divider
      - section: FOURIER OPTICS AND IMAGING
        contents:
          - section: "Lecture 5"
            contents:
              - text: Fourier Optics I
                href: lectures/lecture05/01-lecture05.qmd
          - section: "Lecture 6"
            contents:
              - text: Fourier Optics II
                href: lectures/lecture06/01-lecture06.qmd
          #- section: "Lecture 6"
          #  contents:
          #- text: Photon Streams
          #  href: lectures/lecture04/02-lecture04.qmd
          #- text: Quantum Optics Primer
          #  href: lectures/lecture04/03-lecture04.qmd
